### ISSUE TITLE
TwoFer: incorrect analysis

### ISSUE THREAD

**Issue by kotp** [exercism/ruby-analyzer#16]
![wrong_analysis](https://user-images.githubusercontent.com/16747/65079324-e436c200-d96c-11e9-9f39-450d0bcac1af.png)

The analyzer mistakenly detects no module level method.

Also, Ruby doesn't really have "functions" but "methods".  Closest thing to functions would be, I think, Proc or lambda.

**Comment by iHiD** [comment]
> Also, Ruby doesn't really have "functions" but "methods". Closest thing to functions would be, I think, Proc or lambda.

If you fancy PRing that bit to website-copy, that'd be great.

> The analyzer mistakenly detects no module level method.

Interesting. Thanks.

**Comment by kotp** [comment]
> > Also, Ruby doesn't really have "functions" but "methods". Closest thing to functions would be, I think, Proc or lambda.
> 
> If you fancy PRing that bit to website-copy, that'd be great.

i suppose I did fancy. ;)
